### ISSUE TITLE
Document how to use replica sets, perhaps add to mongomodel.yml template

### ISSUE THREAD

**Issue by jGRUBBS** [spohlenz/mongomodel#30]
I have been using Wheelhouse CMS for a project for over the last year along with Compose.io (formerly MongoHQ) which recommends using replica sets. For a while I would receive a notice from compose.io that one of my replica sets would be stepping down in favor of the other and I would have to manually switch out the database.yml file. However, after some digging I realized that `mongomodel` supports the use of replicas. I only found this, though, after deeply reviewing the source of `mongomodel`, here in particular:
https://github.com/spohlenz/mongomodel/blob/master/lib/mongomodel/support/configuration.rb#L45

To figure out what replicas should be I had to dig into the `mongo` gem. Also worth noting, `mongomodel` depends on a pretty old version of `mongo` so I had to look back to 1.8.6, they are currently at 1.12.0. There I noticed that replicas where just strings of the hostname and port concatenated.

After reviewing the source I realized that all that need to change was a couple lines of my database.yml (wheelhouse.yml in wheelhouse world).

old config:
```yaml
  production:
    database: database_name
    host: some.host.com
    port: 12345
    username: username
    password: password
```

new config:
```yaml
  production:
    database: database_name
    replicas:
      - some.host.com:12345
      - another.host.com:12345
    username: username
    password: password
```

Anyway, I think this should be simpler for someone to find when they first review the mongomodel readme and perhaps even when they generate the mongomodel.yml.
